host: dev.devops.vuhuydiet.xyz
configServer:
  image:
    tag: 0fc0f62
discoveryServer:
  image:
    tag: 0fc0f62
apiGateway:
  image:
    tag: 0fc0f62
adminServer:
  image:
    tag: 0fc0f62
services:
  customersService:
    image:
      tag: 0fc0f62
  visitsService:
    image:
      tag: 0fc0f62
  vetsService:
    image:
      tag: 0fc0f62
