host: dev.devops.vuhuydiet.xyz
configServer:
  image:
    tag: 84e936b
discoveryServer:
  image:
    tag: 84e936b
apiGateway:
  image:
    tag: 84e936b
adminServer:
  image:
    tag: 84e936b
services:
  customersService:
    image:
      tag: 84e936b
  visitsService:
    image:
      tag: 84e936b
  vetsService:
    image:
      tag: 84e936b
