host: dev.devops.vuhuydiet.xyz

configServer:
  image:
    tag: a15e5d0
discoveryServer:
  image:
    tag: a15e5d0
apiGateway:
  image:
    tag: a15e5d0
adminServer:
  image:
    tag: a15e5d0
services:
  customersService:
    image:
      tag: a15e5d0
  visitsService:
    image:
      tag: a15e5d0
  vetsService:
    image:
      tag: a15e5d0
      
# Observability configuration for staging environment
observability:
  useEmptyDirVolumes: false  # Use PVC for staging (persistent storage)
  grafana:
    serviceType: LoadBalancer  # Use LoadBalancer for staging
