host: dev.devops.vuhuydiet.xyz

# Observability configuration for dev environment
observability:
  useEmptyDirVolumes: true  # Use emptyDir for dev to avoid PVC issues
  grafana:
    serviceType: NodePort  # Use NodePort for dev environment

configServer:
  image:
    tag: a15e5d0
discoveryServer:
  image:
    tag: a15e5d0
apiGateway:
  image:
    tag: a15e5d0
adminServer:
  image:
    tag: a15e5d0
services:
  customersService:
    image:
      tag: a15e5d0
  visitsService:
    image:
      tag: a15e5d0
  vetsService:
    image:
      tag: a15e5d0
