host: dev.devops.vuhuydiet.xyz
configServer:
  image:
    tag: 1934df7
discoveryServer:
  image:
    tag: 1934df7
apiGateway:
  image:
    tag: 1934df7
adminServer:
  image:
    tag: 1934df7
services:
  customersService:
    image:
      tag: 1934df7
  visitsService:
    image:
      tag: 1934df7
  vetsService:
    image:
      tag: 1934df7
# Observability configuration for dev environment
observability:
  useEmptyDirVolumes: false # Use PVC for persistent storage on DigitalOcean
  tolerateMemoryPressure: true
  prometheus:
    storage: 4Gi # Smaller size for dev
  grafana:
    serviceType: LoadBalancer
    storage: 1Gi # Smaller size for dev
  loki:
    storage: 2Gi # Smaller size for dev
