host: undefined

configServer:
  name: config-server
  image:
    name: vuhuydiet/spring-petclinic-config-server
    tag: latest
  port: 8888
  targetPort: 8888
  serviceType: ClusterIP

discoveryServer:
  name: discovery-server
  image: 
    name: vuhuydiet/spring-petclinic-discovery-server
    tag: latest
  port: 8761
  targetPort: 8761
  serviceType: ClusterIP

services:
  customersService:
    name: customers-service
    image: 
      name: vuhuydiet/spring-petclinic-customers-service
      tag: latest
    port: 8081
    targetPort: 8081
    serviceType: ClusterIP
  
  visitsService:
    name: visits-service
    image: 
      name: vuhuydiet/spring-petclinic-visits-service
      tag: latest
    port: 8082
    targetPort: 8082
    serviceType: ClusterIP

  vetsService:
    name: vets-service
    image:
      name: vuhuydiet/spring-petclinic-vets-service
      tag: latest
    port: 8083
    targetPort: 8083
    serviceType: ClusterIP

  apiGateway:
    name: api-gateway
    image: 
      name: vuhuydiet/spring-petclinic-api-gateway
      tag: latest
    port: 8080
    targetPort: 8080
    serviceType: ClusterIP

  adminServer:
    name: admin-server
    image: 
      name: vuhuydiet/spring-petclinic-admin-server
      tag: latest
    port: 9090
    targetPort: 9090
    serviceType: ClusterIP

# Observability Stack Configuration
observability:
  # Use emptyDir volumes for development/testing to avoid PVC issues
  useEmptyDirVolumes: true
  tolerateMemoryPressure: false
  prometheus:
    name: prometheus
    image:
      name: prom/prometheus
      tag: v2.45.0
    port: 9090
    targetPort: 9090
    serviceType: ClusterIP
    retention: 15d
    storage: 8Gi
    
  grafana:
    name: grafana
    image:
      name: grafana/grafana
      tag: 10.0.0
    port: 3000
    targetPort: 3000
    serviceType: LoadBalancer
    adminUser: admin
    adminPassword: admin123
    storage: 2Gi
    
  loki:
    name: loki
    image:
      name: grafana/loki
      tag: 2.9.0
    port: 3100
    targetPort: 3100
    serviceType: ClusterIP
    storage: 5Gi
    
  zipkin:
    name: zipkin
    image:
      name: openzipkin/zipkin
      tag: 2.24
    port: 9411
    targetPort: 9411
    serviceType: ClusterIP
