# Config Server deployment - must be deployed first
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.configServer.name }}
  labels:
    app: {{ .Values.configServer.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.configServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.configServer.name }}
    spec:
      containers:
      - name: {{ .Values.configServer.name }}
        image: "{{ .Values.configServer.image.name }}:{{ .Values.configServer.image.tag }}"
        ports:
        - containerPort: {{ .Values.configServer.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        # Observability configuration
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,prometheus,metrics"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "always"
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
          value: "true"
        - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
          value: "1.0"
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: "http://{{ .Values.observability.zipkin.name }}:{{ .Values.observability.zipkin.port }}/api/v2/spans"
        - name: LOGGING_PATTERN_CONSOLE
          value: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.configServer.name }}
spec:
  selector:
    app: {{ .Values.configServer.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.configServer.port }}
    targetPort: {{ .Values.configServer.targetPort }}
  type: {{ .Values.configServer.serviceType}}