{{- range $name, $service := .Values.services }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  labels:
    app: {{ $service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      initContainers:
      - name: wait-for-discovery-server
        image: busybox
        command:
        - sh
        - -c 
        - until nc -z {{ $.Values.discoveryServer.name }} {{ $.Values.discoveryServer.port }}; do echo waiting for config-server; sleep 2; done;

      containers:
      - name: {{ $service.name }}
        image: "{{ $service.image.name }}:{{ $service.image.tag }}"
        ports:
        - containerPort: {{ $service.port }}
        env:
        - name: CONFIG_SERVER_URL
          value: "http://{{ $.Values.configServer.name }}:{{ $.Values.configServer.port }}"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: {{ $service.name}}
        # Observability configuration
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,prometheus,metrics"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "always"
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
          value: "true"
        - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
          value: "1.0"
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: "http://{{ $.Values.observability.zipkin.name }}:{{ $.Values.observability.zipkin.port }}/api/v2/spans"
        - name: LOGGING_PATTERN_CONSOLE
          value: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
spec:
  selector:
    app: {{ $service.name }}
  ports:
  - protocol: TCP
    port: {{ $service.port }}
    targetPort: {{ $service.targetPort }}
  type: {{ $service.serviceType}}
---
{{- end }}