# Admin Server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: {{ .Values.image }}
        ports:
        - containerPort: 9090
        env:
        - name: CONFIG_SERVER_URL
          value: http://config-server:8888
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: admin-server
  ports:
  - port: 9090
    targetPort: 9090
    name: admin
  type: NodePort
