# Customers Service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
      - name: customers-service
        image: ${DOCKER_HUB_USERNAME}/petclinic-customers-service:${TAG}
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: CONFIG_SERVER_URL
          value: http://config-server:8888
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-server:8761/eureka/
        readinessProbe:
          httpGet:
            port: 8081
            path: /actuator/health
          initialDelaySeconds: 60
          periodSeconds: 5
        livenessProbe:
          httpGet:
            port: 8081
            path: /actuator/health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: customers-service
  ports:
  - port: 8081
    targetPort: 8081
    name: customers
  type: ClusterIP