# Discovery Server (Eureka) deployment - must be deployed second
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: {{ .Values.image }}
        ports:
        - containerPort: 8761
        env:
        - name: CONFIG_SERVER_URL
          value: http://config-server:8888
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: discovery-server
  ports:
  - port: 8761
    targetPort: 8761
    name: discovery
  type: NodePort